### ISSUE TITLE
Wallet balance 0 despite many confs on deposit tx.

### ISSUE THREAD

**Issue by valentinewallace** [lightninglabs/lightning-app#1202]
User report: "Hi guys, something strange has happened. I send a small amount to the wallet's address, there are 90 confirmations but my balance on the wallet is still 0."

**Comment by solenya666** [comment]
Same here, already more than enough confirmations but balance 0. I am located in China, could be somehow related to the great firewall?

**Comment by leggii** [comment]
Same issue.

Plenty of confirmations, the address definitely received the amount, as it appears when looking up the address on the blockchain. But nothing showing in the app. 

I reinstalled the app, restored with the keys, after trying to sync, the app now continuously crashes.

**Comment by phideas** [comment]
Same issue, located in Europe. @solenya666 I restored my seed on desktop wallet to access my funds. Hope it helps until this bug get fixed.

**Comment by solenya666** [comment]
Thanks @phideas, no problem with the funds, just was hoping to play around with a mobile lightning app :)

**Comment by solenya666** [comment]
Just reinstalled twice, the app crashes, both times around the same block of the sync (582140 and 582138)

**Comment by valentinewallace** [comment]
@solenya666 @leggii @phideas Hi, thanks for the reports. Crash on restore is fixed in lnd master and the fix will be included in the next app release!

**Comment by solenya666** [comment]
@valentinewallace what about the 0 balance? and when is the net release :)

**Comment by rick-kln** [comment]
I'm also still experiencing the $0 balance issue, I'm on iOS. Sent 0.001 BTC to the app. Waited until about 1000 confirmations and a fully synced lightning app. Still had 0 balance. 

Deleted the app and restored from backup key, seemed to work and sync again. Now more than 3000 confirmations still $0 balance in the app. Also checked the address in the app again, it's definitely the same address that received the funds.
