### ISSUE TITLE
Unable to query bootstrapper BOLT-0010 DNS Seed

### ISSUE THREAD

**Issue by Gatulibu** [lightninglabs/lightning-app#26]
After (successfully) syncing the chain the client doesn't establish any channels.

The log shows:

```
lnd: 2017-10-13 16:54:21.005 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd: 2017-10-13 16:54:21.009 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [nodes.lightning.directory]
lnd: 2017-10-13 16:54:21.319 [ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [nodes.lightning.directory]: lookup _nodes._tcp.nodes.lightning.directory: dnsquery: DNS server failure. 2017-10-13 16:54:21.319 [INF] DISC: Obtained 0 addrs to bootstrap network with
lnd: 2017-10-13 16:54:22.697 [INF] RPCS: [listchannels] fetched 0 channels from DB
```

(repeats every couple seconds)

I've tried restarting the client and turning off windows firewall.

I can ping the server from a command prompt without any problems:
```
C:\>ping nodes.lightning.directory

Pinging nodes.lightning.directory [45.77.115.33] with 32 bytes of data:
Reply from 45.77.115.33: bytes=32 time=121ms TTL=56
Reply from 45.77.115.33: bytes=32 time=120ms TTL=56
Reply from 45.77.115.33: bytes=32 time=120ms TTL=56
Reply from 45.77.115.33: bytes=32 time=123ms TTL=56

Ping statistics for 45.77.115.33:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 120ms, Maximum = 123ms, Average = 121ms
```
	
System: Windows 7 64bit

**Comment by dummyacct7** [comment]
Also encountering the same issue on Win7 64bit. I'm also running behind a VPN, but am able to successfully ping the server through command prompt without issue.

**Comment by Roasbeef** [comment]
Are you manually able to perform the following (or similar DNS query)?
```
$ dig nodes.lightning.directory SRV
```

In the past I've seen that certain DNS resolvers don't like the queries the DNS seed returns as they're too large. If I find myself behind such a resolver, I find that manually switching my `nameserver` to `8.8.8.8` does the trick.

**Comment by tomywomy** [comment]
tried changing name server to 8.8.8.8, getting very similar problem:

```
lnd: 2017-10-14 08:12:38.311 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd: 2017-10-14 08:12:38.320 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [nodes.lightning.directory]
lnd: 2017-10-14 08:12:38.900 [INF] DISC: Obtained 6 addrs to bootstrap network with
lnd: 2017-10-14 08:12:39.028 [ERR] SRVR: unable to connect to 028c620eb95c3907a779adf9c47612973b70c322e5b60a21886947867439ff63e6@45.77.115.33:9735: EOF
lnd: 2017-10-14 08:12:39.029 [ERR] SRVR: unable to connect to 03c1db3cf5408ddebbebfb7f539560538752a89a4651943beca20f625a76626bf2@45.77.115.33:9735: EOF
lnd: 2017-10-14 08:12:39.034 [ERR] SRVR: unable to connect to 0380aa549dbfbd25147e4269dcfef23236ebe3ce453956141058e8bc87022c420e@45.77.115.33:9735: EOF
lnd: 2017-10-14 08:12:39.038 [ERR] SRVR: unable to connect to 02f9b5a65379a4b29a47be912dcab94a98ae596a9fcc7456a78a7c8674dce8c096@45.77.115.33:9735: EOF
lnd: 2017-10-14 08:12:39.109 [ERR] SRVR: unable to connect to 020178567c0f881b579a7ddbcd8ce362a33ebba2b3c2d218e667f7e3b390e40d4e@45.32.138.203:9735: EOF
lnd: 2017-10-14 08:12:39.113 [ERR] SRVR: unable to connect to 034aba246b061b963ea8ca250a1fa3e86797bf8de80a43010a63d78f837447c337@45.32.138.203:9735: EOF
lnd: 2017-10-14 08:12:43.331 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters 2017-10-14 08:12:43.332 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2017-10-14 08:12:48.351 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters 2017-10-14 08:12:48.351 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2017-10-14 08:12:49.018 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-10-14 08:12:53.707 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2017-10-14 08:12:53.707 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2017-10-14 08:13:00.988 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters 2017-10-14 08:13:00.988 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2017-10-14 08:13:06.472 [INF] BTCN: Disconnecting peer 127.0.0.1:18333 (outbound), cannot serve compact filters
lnd: 2017-10-14 08:13:06.472 [INF] BTCN: Lost peer 127.0.0.1:18333 (outbound)
lnd: 2017-10-14 08:13:08.783 [INF] RPCS: [listchannels] fetched 0 channels from DB
```

**Comment by Gatulibu** [comment]
```
$ dig nodes.lightning.directory SRV

; <<>> DiG 9.11.0-P5 <<>> nodes.lightning.directory SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 32570
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nodes.lightning.directory.     IN      SRV

;; Query time: 403 msec
;; SERVER: 192.168.2.1#53(192.168.2.1)
;; WHEN: Sat Oct 14 15:52:58 CEST 2017
;; MSG SIZE  rcvd: 54
```

After changing the DNS to 8.8.8.8 I get:

```
$ dig nodes.lightning.directory SRV

; <<>> DiG 9.11.0-P5 <<>> nodes.lightning.directory SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 50591
;; flags: qr rd ra; QUERY: 1, ANSWER: 25, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;nodes.lightning.directory.	IN	SRV

;; ANSWER SECTION:
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1q2vfg26t4ealk73v9tnf03csaj60nzkup2rymsvqnlhdqa0dyvryuq6ddc3.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1q260p23l6c2xgn97wkhjxr0jytv7cyns44f6k5frhlkxgu2qhdrssqrhf86.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qvls2xyuyq9egcyha59grcw50mqmswa9xsm8p52sqev6ca97y809zad32h0.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1q2v9tkdag4xvlnfa23r4nsxznhzunfvdp275ax9jc8ghauujuryax7f9xpt.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qwvjmrh6gpue2kzpe3fu62gfjq8x8n3wyetdkusklvvgzvp059lkwqxp7zr.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qgqhs4nup7ypk4u60hdumr8rv23nawazk0pdyx8xvlm78vususx5uxqexfs.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1q28vaxa4kdxzuu4vl8lvwspmyqd385kacejx0czujpsf7fyndh3vky06auq.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1q0apa4yg9kcsffxr5grcz88apwv6zd4ntmwt5gjfpm5huwx0l3d2xql0fga.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1q0qak084gzxaawltldl489tq2wr492y6gegegwlv5g8kyknkvf4lyhm02lr.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1q2fuh9a2cal2e3fh04mpvs83k50thg6sjq5qrcd2v2znlfau8g0nqmchkfl.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1q0x7y4x9pk028q7he6et7d69ul698jmy7pvj60scwkzrev8t0xt2crt97yr.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qvq3uusdxm4u2jdpjkgl8z993yvd6dde74g8h3qmemm2paypzakj6xrhjxk.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qfnpwe8kfmzk8n37hdnp33wjy5mkxnpsqw9mwsx79vqkr37vunk0st8qsxn.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qtumtfjn0xjt9xj8h6gjmj4ef2v2ukt2nlx8g4483f7gvaxuarqfvmrau9t.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qg7me7un5jx2uyqap30hst39svkeh8wqdvge7js69wdjuyqegujg5v38n77.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qtugdp0sq9guzu4g8342s2apgkn05u2dmujeznfpcze2mzwk927pvwleuq0.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qvslqgsakdyr92nk6xngeux79l4ske9dx0hyjfzvy8de5weqpgcvqk6j07m.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qvg9g9tzv9ngjm6egr6hdpz4gp0c8gufc444ltj07rl693j2pdavcynh799.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1q2xxyr4etsus0fme4huugasjjuahpsezukmq5gvgd9rcvapela37vlwmsvv.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qwq254yah77j29r7gf5aelhjxgmwhc7wg5u4v9qstr5tepcz93pqu04fq88.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1q2vj048v7edjjg0v79udrm0ay896jgjlwl3y7hlcgpa7rffmmesay0s09t0.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qfypr9ku0augx3q7vlutpnxzkh4hx0909v9p6a76rke3dsmvjll6ky7m3dt.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qwsddt350vgxhzfc6dtf35n0vw7q6dhsqe7xfk4pugfsh4fywmx8wg9u86w.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qd9t5frtqcdev04gegjs58arapne00udaq9yxqg2v0tclqm5glpnwv32xg3.nodes.lightning.directory.
nodes.lightning.directory. 59	IN	SRV	10 10 9735 ln1qgv4fwn9w4ekckp2w7zaraf4vu200u450dmnfe0wyrlw0wa8sra6ksckl98.nodes.lightning.directory.

;; Query time: 124 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Oct 14 15:58:19 CEST 2017
;; MSG SIZE  rcvd: 2754
```

Unfortunately the client still doesn't establish any channels:

```
lnd: 2017-10-14 16:01:30.472 [INF] CRTR: Filtering chain using 0 channels active
lnd: 2017-10-14 16:01:30.472 [INF] SRVR: Initializing peer network boostrappers! 2017-10-14 16:01:30.472 [INF] CMGR: Server listening on [::]:9735
lnd: 2017-10-14 16:01:30.472 [INF] SRVR: Creating DNS peer boostrapper with seeds: [nodes.lightning.directory] 2017-10-14 16:01:30.473 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd: 2017-10-14 16:01:30.473 [INF] ATPL: Instantiating autopilot with cfg: (*main.autoPilotConfig)(0xc0424afac0)({ Active: (bool) true, MaxChannels: (int) 5, Allocation: (float64) 0.6 })
lnd: 2017-10-14 16:01:30.473 [INF] ATPL: Autopilot Agent starting
lnd: 2017-10-14 16:01:30.473 [INF] ATPL: Processing new external signal
lnd: 2017-10-14 16:01:30.473 [INF] ATPL: Triggering attachment directive dispatch
lnd: 2017-10-14 16:01:30.479 [INF] ATPL: No eligible candidates to connect to
lnd: 2017-10-14 16:01:30.639 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [nodes.lightning.directory]
lnd: 2017-10-14 16:01:32.438 [INF] DISC: Obtained 3 addrs to bootstrap network with
lnd: 2017-10-14 16:01:32.705 [ERR] SRVR: unable to connect to 0380aa549dbfbd25147e4269dcfef23236ebe3ce453956141058e8bc87022c420e@45.77.115.33:9735: EOF
lnd: 2017-10-14 16:01:32.705 [ERR] SRVR: unable to connect to 02661764f64ec563ce3ebb6618c5d22537634c30038bb740de2b0161c7cce4ecf8@45.77.115.33:9735: EOF
lnd: 2017-10-14 16:01:32.782 [ERR] SRVR: unable to connect to 03105415626166896f5940f5768455405f83a389c56b5fae4ff0ffa2c64a0b7acc@45.32.138.203:9735: EOF
lnd: 2017-10-14 16:01:47.438 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
lnd: 2017-10-14 16:01:47.603 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [nodes.lightning.directory]
lnd: 2017-10-14 16:01:49.215 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-10-14 16:01:50.481 [INF] DISC: Obtained 6 addrs to bootstrap network with
lnd: 2017-10-14 16:01:50.572 [ERR] SRVR: unable to connect to 0209a91b81315b3d9abb2b0a02f34039e1f6e4129476fcfa59bac0f509fe5b29aa@195.181.243.196:9735: EOF
lnd: 2017-10-14 16:01:50.760 [ERR] SRVR: unable to connect to 02f9b5a65379a4b29a47be912dcab94a98ae596a9fcc7456a78a7c8674dce8c096@45.77.115.33:9735: EOF
lnd: 2017-10-14 16:01:50.761 [ERR] SRVR: unable to connect to 028c620eb95c3907a779adf9c47612973b70c322e5b60a21886947867439ff63e6@45.77.115.33:9735: EOF
lnd: 2017-10-14 16:01:50.762 [ERR] SRVR: unable to connect to 03c1db3cf5408ddebbebfb7f539560538752a89a4651943beca20f625a76626bf2@45.77.115.33:9735: EOF
lnd: 2017-10-14 16:01:50.826 [ERR] SRVR: unable to connect to 02481196dc7f7883441e67f8b0ccc2b5eb733caf2b0a1d77da1db316c36c97ffab@45.32.138.203:9735: EOF
lnd: 2017-10-14 16:01:51.593 [ERR] SRVR: unable to connect to 0321f0221db34832aa76d1a68cf0de2feb0b64ad33ee49244c21db9a3b200a30c0@185.69.52.198:9735: dial tcp 185.69.52.198:9735: connectex: No connection could be made because the target machine actively refused it.
lnd: 2017-10-14 16:02:09.147 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-10-14 16:02:29.147 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-10-14 16:02:49.147 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-10-14 16:03:07.006 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-10-14 16:03:08.995 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-10-14 16:03:29.166 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-10-14 16:03:49.159 [INF] RPCS: [listchannels] fetched 0 channels from DB
lnd: 2017-10-14 16:04:09.151 [INF] RPCS: [listchannels] fetched 0 channels from DB
```

**Comment by tomywomy** [comment]
I have the same problem but am manually able to establish channels.
02177255e151c6312251477259d5daf769b06e2a6b4382f464a320ba57c5d48459@99.229.46.118 (for now)

**Comment by Gatulibu** [comment]
I left the client running for about 30min, after a restart a channel is now establishing.

**Comment by tomywomy** [comment]
I had to move my application into the Applications directory and it began working fine.

**Comment by Emzy** [comment]
Same Problem here.
8.8.8.8 as DNS works. My Fritzbox / ISP don't work.

$ dig nodes.lightning.directory SRV

; <<>> DiG 9.9.7-P3 <<>> nodes.lightning.directory SRV
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 59701
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;nodes.lightning.directory.	IN	SRV

;; Query time: 312 msec
;; SERVER: 192.168.99.1#53(192.168.99.1)
;; WHEN: Sat Oct 14 19:59:49 CEST 2017
;; MSG SIZE  rcvd: 54

**Comment by Roasbeef** [comment]
Fixed by https://github.com/lightningnetwork/lnd/commit/5b226a9d37b3a9d0b2f874f40d50d4c575ff0e55 

Closing.

**Comment by mariodian** [comment]
I'm using the latest 0.4 beta (didn't compile myself) and I'm still getting these errors:

```
Attempting to bootstrap with: Authenticated Channel Graph
2018-03-17 00:01:32.992 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory]]
2018-03-17 00:01:33.919 [ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory]]: dns: domain must be fully qualified
2018-03-17 00:01:33.919 [INF] DISC: Obtained 0 addrs to bootstrap network with
```

I'm running Ubuntu 17.04.

**Comment by Roasbeef** [comment]
The DNS seeding has been modified as there's now a testnet and mainnet
seed. As a result the current packaged binary won't be able to take
advantage of auto bootstrap. We'll be releasing a new version for folks on
testnet to continue to experiment with soon.

**Comment by mariodian** [comment]
I just installed lnd from the source and I'm still getting the same issue.

**Comment by Roasbeef** [comment]
Is this related to the application? It pre packages the binary of a prior
version of the application

**Comment by adolfosrs** [comment]
Facing the same problem here. Any ideas or workaround?

**Comment by Roasbeef** [comment]
The mainnet DNS seeding hasn't been set up yet as we were waiting for nodes to update so we would start to seed _fresh_ nodes.

**Comment by polkhovsky** [comment]
So then this is normal and we should simply wait?

**Comment by MrRickle** [comment]
I think I have the same or similar thing? I have not run lnd before, don't really know what i'm doing, trying to setup with bitcoind mainnet (runs armory wallet fine). I'm using lnd 0.4 beta (didn't compile myself) on linux light,  it synced up. then I'm getting the following repeating over and over.  
2018-03-16 16:04:31.418 [DBG] SRVR: Attempting to obtain 3 more network peers
2018-03-16 16:04:31.418 [INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
2018-03-16 16:04:31.418 [TRC] DISC: Querying for 6 addresses
2018-03-16 16:04:31.419 [TRC] DISC: Ending hash accumulator state: 5a72a45ab5d9c6a746350e8347d7d76b3596e10d7589d8b756135fc38590e55f
2018-03-16 16:04:31.419 [INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory]]
2018-03-16 16:04:31.419 [TRC] DISC: Querying for 6 addresses
2018-03-16 16:04:31.528 [TRC] DISC: Unable to lookup SRV records via primary seed, falling back to secondary
2018-03-16 16:04:31.528 [TRC] DISC: Attempting to query fallback DNS seed
2018-03-16 16:04:31.642 [ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory]]: dns: domain must be fully qualified
2018-03-16 16:04:31.642 [INF] DISC: Obtained 0 addrs to bootstrap network with

**Comment by polkhovsky** [comment]
@MrRickle I get the same messages.

**Comment by MDrollette** [comment]
In the meantime, here's a couple nodes to get bootstrapped.

```
lncli connect 031feee8045899c658eec2b6f2f6da6e4bdd7baabdc61bdc017761577342fbd011@76.184.81.28:9735

lncli connect 024a2e265cd66066b78a788ae615acdc84b5b0dec9efac36d7ac87513015eaf6ed@52.16.240.222:9735

lncli connect 02ad6fb8d693dc1e4569bcedefadf5f72a931ae027dc0f0c544b34c1c6f3b9a02b@167.99.50.31:9735
```

**Comment by MrRickle** [comment]
Cool! that makes it go!

**Comment by ranchalp** [comment]
Should you come up with the issue here, make sure you have your backend fully synced.

**Comment by RobinTick** [comment]
Experiencing this same issue on the newly released mobile app on Android.

### Description
Lightning app on Android can't retrieve initial bootstrap peers.
The log loops these messages:

[ERR] SRVR: Unable to retrieve initial bootstrap peers: no addresses found
[INF] DISC: Attempting to bootstrap with: Authenticated Channel Graph
[INF] DISC: Attempting to bootstrap with: BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory]]
[ERR] DISC: Unable to query bootstrapper BOLT-0010 DNS Seed: [[nodes.lightning.directory soa.nodes.lightning.directory]]: lookup soa.nodes.lightning.directory: No address associated with hostname

I have tried my home wifi and 4G, both presented the same issue.
I have set my phone's primary and secondary DNS to 8.8.8.8 and 8.8.4.4 on wifi but the problem persisted.
An Ubuntu Linux PC running the Lightning desktop app connects to the same router through ethernet and has no such connection issues.

### Steps to reproduce the behavior
Using Lightning app on a Samsung Galaxy S9+ running Android 9.
Install the app.
Ignore for couple hours.
Create 24 word seed.
Block sync takes 1 second.
Do not send Bitcoin to wallet yet.
Check logs, see recurring error.

### Expected behavior
Build channel graph automatically.

### Actual behavior
Connection issues prevent building channel graph.

### Screenshot and/or logs if applicable
![Screenshot_20190622-110027_Lightning](https://user-images.githubusercontent.com/9660062/59962847-2164f280-94eb-11e9-96e6-3e1a87584082.jpg)

Here is a dig from said PC on the same network:

$ dig nodes.lightning.directory soa.nodes.lightning.directory

; <<>> DiG 9.11.5-P1-1ubuntu2.4-Ubuntu <<>> nodes.lightning.directory soa.nodes.lightning.directory
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 57384
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;nodes.lightning.directory.	IN	A

;; Query time: 3050 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: za jun 22 13:07:03 CEST 2019
;; MSG SIZE  rcvd: 54

;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 6335
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;soa.nodes.lightning.directory.	IN	A

;; Query time: 1543 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: za jun 22 13:07:04 CEST 2019
;; MSG SIZE  rcvd: 58

**Comment by tserowski** [comment]
I have the exact same issue as @RobinTick 
Other than him I receive no SERVFAIL on digging the hostnames.
